---
- name: install mongo
  hosts: all
  become: true
  tasks:
  - name: add ppa key
    apt_key:
      id: EA312927
      keyserver: keyserver.ubuntu.com
      state: present
    tags: install

  - name: add repo sources.list
    apt_repository:
      repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu {{ansible_distribution_release}}/mongodb-org/3.2 multiverse
      state: present
    tags: install

  - name: install mongo
    apt:
      name: mongodb-org
      state: present
      update_cache: yes
    tags: install

  - name: enable mongo
    systemd:
      name: mongod
      enabled: yes
    tags: install
