---
- name: Configure MongoDB hosts
  hosts:
    - tag_reddit-db-*
    - db
  become: true
  roles:
    - db

#thanks to loktionovam_infra
  pre_tasks:
    - name: Create ad-hoc group (group all found hosts under inventory group "db" for group_vars)
      group_by:
        key: "db"
